# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEPY_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerweight',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerweight',
            name='type',
            field=models.CharField(choices=[('short_comment', 'short_comment'), ('long_comment', 'long_comment'), ('only_value', 'only_value'), ('report', 'report')], default='short_comment', max_length=16),
        ),
    ]
