# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEPY_new', '0002_auto_20170611_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='long_text',
        ),
        migrations.RemoveField(
            model_name='answerweight',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='answersThatEnable',
            field=models.ManyToManyField(to='HEPY_new.Answer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='short_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerweight',
            name='type',
            field=models.CharField(choices=[('risk', 'risk')], default='risk', max_length=16),
        ),
    ]
