# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEPY_new', '0003_auto_20170612_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerweight',
            name='type',
            field=models.CharField(choices=[('risk', 'risk'), ('hepatitis_a_b', 'hepatitis_a_b'), ('not_a_b', 'not_a_b')], default='risk', max_length=16),
        ),
    ]
