# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEPY_new', '0004_auto_20170712_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerweight',
            name='type',
            field=models.CharField(choices=[('risk', 'risk'), ('hepatitis_a_b', 'hepatitis_a_b'), ('not_a_b', 'not_a_b'), ('order', 'order')], default='risk', max_length=16),
        ),
    ]
